name: "Get Testrail Run Info"
description: "A GitHub Action to fetch Testrail run results for future steps."
author: "Q4 Inc"
inputs:
  network_url:
    required: true
    description: The Testrail account domain name
  username:
    required: true
    description: The username associated with the test runner
  api_key:
    required: true
    description: The API key associated with the username
  run_id:
    required: true
    description: The ID of the Testrail run
  current_branch:
    required: true
    description: Used to determine the related tests, e.g., QP-XXX
  project_id:
    required: false
    description: The project ID of the Testrail project
runs:
  using: 'node12'
  main: 'dist/index.js'
